<?php

include ('../db/db3.php');
include('class.phpmailer.php');
include('PHPMailerAutoload.php');

define('GUSER', 'info@tipfriendly.com'); // GMail username
define('GPWD', 'Jamaica$1'); // GMail password

function smtpmailer_Discipline($to, $from, $subject, $attatch) {
//global $error;

    $mail = new PHPMailer;  // create a new object

    $mail->isSMTP(); // enable SMTP
    //$mail->SMTPDebug = 2;  // debugging: 1 = errors and messages, 2 = messages only
    $mail->SMTPAuth = true;  // authentication enabled
    $mail->SMTPSecure = 'tls'; // secure transfer enabled REQUIRED for GMail
    $mail->SMTPAutoTLS = false;
    $mail->Host = 'smtp.gmail.com';
    $mail->Port = 25;
    $mail->Username = GUSER;
    $mail->Password = GPWD;
    $mail->SetFrom(GUSER, 'Tip Friendly Society');
    $mail->Subject = $subject;
    $mail->Body = 'Generated by ' . $from;
    $mail->AddAddress($to);
    $mail->addAttachment($attatch);
    $mail->isHTML(true);

    if (!$mail->send()) {
        //$error = 'Mail error: ' . $mail->ErrorInfo;
        echo 'Message could not be sent.';
        echo 'Mailer Error: ' . $mail->ErrorInfo;
        exit;
        //return false;
    } else {
        //$error = 'Message sent!';
        echo 'message sent';
        exit;
        //return true;
    }
}

function smtpmailer_LeaveAcceptMan($to, $from, $name, $dept, $type, $numdays, $startdate, $enddate) {
//global $error;

    $mail = new PHPMailer;  // create a new object

    $mail->isSMTP(); // enable SMTP
    //$mail->SMTPDebug = 2;  // debugging: 1 = errors and messages, 2 = messages only
    $mail->SMTPAuth = true;  // authentication enabled
    $mail->SMTPSecure = 'tls'; // secure transfer enabled REQUIRED for GMail
    $mail->SMTPAutoTLS = false;
    $mail->Host = 'smtp.gmail.com';
    $mail->Port = 25;
    $mail->Username = GUSER;
    $mail->Password = GPWD;
    $mail->SetFrom(GUSER, 'Tip Friendly Society');
    $mail->Subject = "Leave Application for $name from $from";
    $mail->Body = "Accepted $name of the $dept Department for $type leave application for $numdays from $startdate to $enddate, please review and finalize";
    $mail->AddAddress($to);
    //$mail->addAttachment($attatch);
    $mail->isHTML(true);



    if (!$mail->send()) {
        $error = 'Mail error: ' . $mail->ErrorInfo;
        echo 'Message could not be sent.';
        echo 'Mailer Error: ' . $mail->ErrorInfo;
        //exit;
        //return false;
    } else {
        //$error = 'Message sent!';
        echo 'message sent';

        //exit;
        //return true;
    }
}

function smtpmailer_LeaveRejectMan($to, $from, $name, $dept, $type, $numdays, $startdate, $enddate) {
//global $error;

    $mail = new PHPMailer;  // create a new object

    $mail->isSMTP(); // enable SMTP
    //$mail->SMTPDebug = 2;  // debugging: 1 = errors and messages, 2 = messages only
    $mail->SMTPAuth = true;  // authentication enabled
    $mail->SMTPSecure = 'tls'; // secure transfer enabled REQUIRED for GMail
    $mail->SMTPAutoTLS = false;
    $mail->Host = 'smtp.gmail.com';
    $mail->Port = 25;
    $mail->Username = GUSER;
    $mail->Password = GPWD;
    $mail->SetFrom(GUSER, 'Tip Friendly Society');
    $mail->Subject = "Leave Application for $name::email from $from";
    $mail->Body = "I rejected the leave application of"
            . " $name of the $dept Department for $type leave application for $numdays from $startdate to $enddate, please review and finalize";
    $mail->AddAddress($to);
    //$mail->addAttachment($attatch);
    $mail->isHTML(true);



    if (!$mail->send()) {
        $error = 'Mail error: ' . $mail->ErrorInfo;
        echo 'Message could not be sent.';
        echo 'Mailer Error: ' . $mail->ErrorInfo;
        //exit;
        //return false;
    } else {
        //$error = 'Message sent!';
        echo 'message sent';

        //exit;
        //return true;
    }
}


function smtpmailer_LeaveAcceptHR($to, $from, $name, $dept, $type, $numdays, $startdate, $enddate) {
//global $error;

    $mail = new PHPMailer;  // create a new object

    $mail->isSMTP(); // enable SMTP
    //$mail->SMTPDebug = 2;  // debugging: 1 = errors and messages, 2 = messages only
    $mail->SMTPAuth = true;  // authentication enabled
    $mail->SMTPSecure = 'tls'; // secure transfer enabled REQUIRED for GMail
    $mail->SMTPAutoTLS = false;
    $mail->Host = 'smtp.gmail.com';
    $mail->Port = 25;
    $mail->Username = GUSER;
    $mail->Password = GPWD;
    $mail->SetFrom(GUSER, 'Tip Friendly Society');
    $mail->Subject = "Leave Accepted";
    $mail->Body = "Dear $name of the $dept Department  your $type leave application for $numdays from $startdate to $enddate has been Accepted ";
    $mail->AddAddress($to);
    //$mail->addAttachment($attatch);
    $mail->isHTML(true);



    if (!$mail->send()) {
        //$error = 'Mail error: ' . $mail->ErrorInfo;
        echo 'Message could not be sent.';
        echo 'Mailer Error: ' . $mail->ErrorInfo;
        //exit;
        //return false;
    } else {
        //$error = 'Message sent!';
        echo 'message sent';

        //exit;
        //return true;
    }
}


function smtpmailer_LeaveRejectHR($to, $from, $name, $dept, $type, $numdays, $startdate, $enddate) {
//global $error;

    $mail = new PHPMailer;  // create a new object

    $mail->isSMTP(); // enable SMTP
    //$mail->SMTPDebug = 2;  // debugging: 1 = errors and messages, 2 = messages only
    $mail->SMTPAuth = true;  // authentication enabled
    $mail->SMTPSecure = 'tls'; // secure transfer enabled REQUIRED for GMail
    $mail->SMTPAutoTLS = false;
    $mail->Host = 'smtp.gmail.com';
    $mail->Port = 25;
    $mail->Username = GUSER;
    $mail->Password = GPWD;
    $mail->SetFrom(GUSER, 'Tip Friendly Society');
    $mail->Subject = "Leave Rejected";
    $mail->Body = "Dear $name of the $dept Department  your $type leave application for $numdays from $startdate to $enddate has been Rejected ";
    $mail->AddAddress($to);
    //$mail->addAttachment($attatch);
    $mail->isHTML(true);



    if (!$mail->send()) {
        //$error = 'Mail error: ' . $mail->ErrorInfo;
        echo 'Message could not be sent.';
        echo 'Mailer Error: ' . $mail->ErrorInfo;
        //exit;
        //return false;
    } else {
        //$error = 'Message sent!';
        echo 'message sent';

        //exit;
        //return true;
    }
}

function smtpmailer_ApplyLeave($to, $from, $name, $dept, $type, $numdays, $startdate, $enddate) {
//global $error;

    $mail = new PHPMailer;  // create a new object
    $url = "<html><a href='http://localhost/HR_APP/HR_APP/LeaveMod/LeaveRequests.php'>Leave Requests</a></html>";
    $mail->isSMTP(); // enable SMTP
    //$mail->SMTPDebug = 1;  // debugging: 1 = errors and messages, 2 = messages only
    $mail->SMTPAuth = true;  // authentication enabled
    $mail->SMTPSecure = 'tls'; // secure transfer enabled REQUIRED for GMail
    $mail->SMTPAutoTLS = false;
    $mail->Host = 'smtp.gmail.com';
    $mail->Port = 25;
    $mail->Username = GUSER;
    $mail->Password = GPWD;
    $mail->SetFrom(GUSER, 'Tip Friendly Society');
    $mail->Subject = "Leave Application";
    $mail->Body = "Generated by: ".$name."<br>"
                    ."$name of the $dept Department has applied for $numdays [$type]. Starting at the $startdate to the $enddate"."<br>"
                    ."$url";
    $mail->AddAddress($to);
    //$mail->addAttachment($attatch);
    $mail->isHTML(true);



    if (!$mail->send()) {
        //$error = 'Mail error: ' . $mail->ErrorInfo;
        echo 'Try Again';
        echo 'Mailer Error: ' . $mail->ErrorInfo;
        //exit;
        //return false;
    } else {
        //$error = 'Message sent!';
        echo 'Applied Succesfully';

        //exit;
        //return true;
    }
}

//smtpmailer_ApplyLeave('a.adams@tipfriendly.com', 'a.thomas@tipfriendly.com', 'Andrew Thomas', 'IT', 'Vacation', '8', '22-09-2016', '23-09-2016');


function smtpmailer_OutstandingLeave($to, $name,$days) {
//global $error;

    $mail = new PHPMailer;  // create a new object
    $url = "<html><a href='http://localhost/HR_APP/HR_APP/LeaveMod/LeaveApply.php'>Leave Apply</a></html>";
    $mail->isSMTP(); // enable SMTP
    //$mail->SMTPDebug = 2;  // debugging: 1 = errors and messages, 2 = messages only
    $mail->SMTPAuth = true;  // authentication enabled
    $mail->SMTPSecure = 'tls'; // secure transfer enabled REQUIRED for GMail
    $mail->SMTPAutoTLS = false;
    $mail->Host = 'smtp.gmail.com';
    $mail->Port = 25;
    $mail->Username = GUSER;
    $mail->Password = GPWD;
    $mail->SetFrom(GUSER, 'Tip Friendly Society');
    $mail->Subject = "Outstanding Leave";
    $mail->Body = "Dear $name it has been noted that you have accumulated $days outstanding leave day(s) over a three year period."
            . "Please rectify by going on leave ASAP to clear off the days.";
    $mail->AddAddress($to);
    //$mail->addAttachment($attatch);
    $mail->isHTML(true);



    if (!$mail->send()) {
        //$error = 'Mail error: ' . $mail->ErrorInfo;
        echo 'Try Again';
        //echo 'Mailer Error: ' . $mail->ErrorInfo;
        exit;
        //return false;
    } else {
        $error = 'Message sent!';
        echo $error;

        //exit;
        //return true;
    }
}

function smtpmailer_LoanApplication($to,$name,$dept) {
//global $error;

    $mail = new PHPMailer;  // create a new object
    //$url = "<html><a href='http://localhost/HR_APP/HR_APP/LeaveMod/LeaveApply.php'>Leave Apply</a></html>";
    $mail->isSMTP(); // enable SMTP
    //$mail->SMTPDebug = 2;  // debugging: 1 = errors and messages, 2 = messages only
    $mail->SMTPAuth = true;  // authentication enabled
    $mail->SMTPSecure = 'tls'; // secure transfer enabled REQUIRED for GMail
    $mail->SMTPAutoTLS = false;
    $mail->Host = 'smtp.gmail.com';
    $mail->Port = 25;
    $mail->Username = GUSER;
    $mail->Password = GPWD;
    $mail->SetFrom(GUSER, 'Tip Friendly Society');
    $mail->Subject = "Loan Application from ".$name." of the ".$dept." Department";
    $mail->Body = "Please Log into the HR Application";
    $mail->AddAddress($to);
    //$mail->addAttachment($attatch);
    $mail->isHTML(true);



    if (!$mail->send()) {
        //$error = 'Mail error: ' . $mail->ErrorInfo;
        echo 'Try Again';
        //echo 'Mailer Error: ' . $mail->ErrorInfo;
        //exit;
        //return false;
    } else {
        $error = 'Message sent!';
        echo $error;

        //exit;
        //return true;
    }
}

function smtpmailer_AccountsApprove($to,$name,$dept) {
//global $error;

    $mail = new PHPMailer;  // create a new object
    //$url = "<html><a href='http://localhost/HR_APP/HR_APP/LeaveMod/LeaveApply.php'>Leave Apply</a></html>";
    $mail->isSMTP(); // enable SMTP
    //$mail->SMTPDebug = 2;  // debugging: 1 = errors and messages, 2 = messages only
    $mail->SMTPAuth = true;  // authentication enabled
    $mail->SMTPSecure = 'tls'; // secure transfer enabled REQUIRED for GMail
    $mail->SMTPAutoTLS = false;
    $mail->Host = 'smtp.gmail.com';
    $mail->Port = 25;
    $mail->Username = GUSER;
    $mail->Password = GPWD;
    $mail->SetFrom(GUSER, 'TIP Friendly Society');
    $mail->Subject = "Loan Application from ".$name." of the ".$dept." Department";
    $mail->Body = "This application has been revised and approved by the Accounts Dept."
            . "Vet and proceed as necessary";
    $mail->AddAddress($to);
    //$mail->addAttachment($attatch);
    $mail->isHTML(true);



    if (!$mail->send()) {
        //$error = 'Mail error: ' . $mail->ErrorInfo;
        echo 'Try Again';
        //echo 'Mailer Error: ' . $mail->ErrorInfo;
        //exit;
        //return false;
    } else {
        $error = 'Message sent!';
        echo $error;

        //exit;
        //return true;
    }
}

function smtpmailer_GMApprove($to,$name,$dept) {
//global $error;

    $mail = new PHPMailer;  // create a new object
    //$url = "<html><a href='http://localhost/HR_APP/HR_APP/LeaveMod/LeaveApply.php'>Leave Apply</a></html>";
    $mail->isSMTP(); // enable SMTP
    //$mail->SMTPDebug = 2;  // debugging: 1 = errors and messages, 2 = messages only
    $mail->SMTPAuth = true;  // authentication enabled
    $mail->SMTPSecure = 'tls'; // secure transfer enabled REQUIRED for GMail
    $mail->SMTPAutoTLS = false;
    $mail->Host = 'smtp.gmail.com';
    $mail->Port = 25;
    $mail->Username = GUSER;
    $mail->Password = GPWD;
    $mail->SetFrom(GUSER, 'TIP Friendly Society');
    $mail->Subject = "Loan Application from ".$name." of the ".$dept." Department";
    $mail->Body = "This application has been Vetted and approved by the AGM."
            . " Disburse the loan";
    $mail->AddAddress($to);
    //$mail->addAttachment($attatch);
    $mail->isHTML(true);



    if (!$mail->send()) {
        //$error = 'Mail error: ' . $mail->ErrorInfo;
        echo 'Try Again';
        //echo 'Mailer Error: ' . $mail->ErrorInfo;
        //exit;
        //return false;
    } else {
        $error = 'Message sent!';
        echo $error;

        //exit;
        //return true;
    }
}

function smtpmailer_GMApprove2($to,$name,$dept, $type, $amount) {
//global $error;

    $mail = new PHPMailer;  // create a new object
    $mail->isSMTP(); // enable SMTP
    //$mail->SMTPDebug = 2;  // debugging: 1 = errors and messages, 2 = messages only
    $mail->SMTPAuth = true;  // authentication enabled
    $mail->SMTPSecure = 'tls'; // secure transfer enabled REQUIRED for GMail
    $mail->SMTPAutoTLS = false;
    $mail->Host = 'smtp.gmail.com';
    $mail->Port = 25;
    $mail->Username = GUSER;
    $mail->Password = GPWD;
    $mail->SetFrom(GUSER, 'TIP Friendly Society');
    $mail->Subject = "Loan Application";
    $mail->Body = "Dear $name of the $dept we would like to inform you that your $type loan request for $ $amount has been approved"
            . ". Please Go to the Accounts Dept to sign the relevant documents.";
    $mail->AddAddress($to);
    //$mail->addAttachment($attatch);
    $mail->isHTML(true);



    if (!$mail->send()) {
        //$error = 'Mail error: ' . $mail->ErrorInfo;
        echo 'Try Again';
        //echo 'Mailer Error: ' . $mail->ErrorInfo;
        //exit;
        //return false;
    } else {
        $error = 'Message sent!';
        echo $error;

        //exit;
        //return true;
    }
}


function smtpmailer_Disburse($to,$name,$dept, $type, $amount) {
//global $error;

    $mail = new PHPMailer;  // create a new object
    $mail->isSMTP(); // enable SMTP
    //$mail->SMTPDebug = 2;  // debugging: 1 = errors and messages, 2 = messages only
    $mail->SMTPAuth = true;  // authentication enabled
    $mail->SMTPSecure = 'tls'; // secure transfer enabled REQUIRED for GMail
    $mail->SMTPAutoTLS = false;
    $mail->Host = 'smtp.gmail.com';
    $mail->Port = 25;
    $mail->Username = GUSER;
    $mail->Password = GPWD;
    $mail->SetFrom(GUSER, 'TIP Friendly Society');
    $mail->Subject = "Loan Application";
    $mail->Body = "Dear $name of the $dept we would like to inform you that your $type loan request for $ $amount has been disbursed.";
    $mail->AddAddress($to);
    //$mail->addAttachment($attatch);
    $mail->isHTML(true);



    if (!$mail->send()) {
        //$error = 'Mail error: ' . $mail->ErrorInfo;
        echo 'Try Again';
        //echo 'Mailer Error: ' . $mail->ErrorInfo;
        //exit;
        //return false;
    } else {
        $error = 'Message sent!';
        echo $error;

        //exit;
        //return true;
    }
}
?>